# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OrthoMap' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrthoMap

  pod 'Mapbox-iOS-SDK', '~> 4.1'

end
